(function () {
  "use strict";

  const ART = {
    e01: "imgs/XtRkKmVa.jpeg",
    e02: "imgs/7Yzr48dq.jpeg",
    e03: "imgs/7SRzrLGg.jpeg",
    e04: "imgs/ajADI1Bq.jpeg",
    e05: "imgs/fdZGaBwi.jpeg",
    e06: "imgs/MXbdfn9t.jpeg",
    e07: "imgs/4r3KWU6Y.jpeg",
    e08: "imgs/4vQeL8h3.jpeg",
    e09: "imgs/NxQEIPzA.jpeg",
    e10: "imgs/CLkWGZ3P.jpeg",
  };

  const BESTIARY = [
    {
      id: "ent01",
      art: ART.e01,
      original: "Star Spawn of Cthulhu",
      stats: { cr: 21, hp: 264, ca: 19 },
      attack: {
        pt: "Garra Psíquica",
        en: "Psychic Claw",
        es: "Garra Psíquica",
      },
      special: {
        pt: "Imunidade: Encantamento e Medo",
        en: "Immunity: Charm and Fear",
        es: "Inmunidad: Encantamiento y Miedo",
        kind: "Imunidade",
      },
      name: {
        pt: "Cria Estelar de Cthulhu",
        en: "Star Spawn of Cthulhu",
        es: "Engendro Estelar de Cthulhu",
      },
      lore: {
        pt: "Entidades ciclópicas gelatinosas verde-escuras. Não respiram, apenas aguardam o alinhamento das constelações nas profundezas das fossas abissais do Pacífico.",
        en: "Cyclopean gelatinous dark-green entities. They do not breathe; they merely await the alignment of the constellations in the depths of the Pacific abyssal trenches.",
        es: "Entidades ciclópeas gelatinosas de un verde oscuro. No respiran; tan solo aguardan la alineación de las constelaciones en las profundidades de las fosas abisales del Pacífico.",
      },
    },
    {
      id: "ent02",
      art: ART.e02,
      original: "Aboleth Sovereign",
      stats: { cr: 15, hp: 135, ca: 17 },
      attack: {
        pt: "Muco Escravizante",
        en: "Enslaving Mucus",
        es: "Mucosidad Esclavizante",
      },
      special: {
        pt: "Desidratação extrema fora da água",
        en: "Extreme dehydration out of water",
        es: "Deshidratación extrema fuera del agua",
        kind: "Fraqueza",
      },
      name: {
        pt: " Aboleth Soberano",
        en: " Aboleth Sovereign",
        es: " Aboleth Soberano",
      },
      lore: {
        pt: "Peixes primordiais que lembram a história do universo desde a sua gênese. Erguem impérios no subterrâneo humano, escravizando mentes com sua telepatia anfíbia.",
        en: "Primordial fish that remember the history of the universe since its genesis. They raise empires beneath humanity, enslaving minds with their amphibious telepathy.",
        es: "Peces primordiales que recuerdan la historia del universo desde su génesis. Erigen imperios en el subsuelo humano, esclavizando mentes con su telepatía anfibia.",
      },
    },
    {
      id: "ent03",
      art: ART.e03,
      original: "Protoplasmic Shoggoth",
      stats: { cr: 19, hp: 210, ca: 15 },
      attack: {
        pt: "Esmagamento Envolvente",
        en: "Engulfing Crush",
        es: "Aplastamiento Envolvente",
      },
      special: {
        pt: " Dano Físico Não-Mágico",
        en: " Non-Magical Physical Damage",
        es: " Daño Físico No Mágico",
        kind: "Imunidade",
      },
      name: {
        pt: "Shoggoth Protoplasmático",
        en: "Protoplasmic Shoggoth",
        es: "Shoggoth Protoplasmático",
      },
      lore: {
        pt: "Massas iridescentes de matéria amorfa, com dezenas de olhos verdes e bocas que se formam e colapsam instantaneamente. Servos criados por deuses, que se rebelaram e devoraram seus criadores.",
        en: "Iridescent masses of amorphous matter, with dozens of green eyes and mouths that form and collapse instantly. Servants created by gods, who rebelled and devoured their creators.",
        es: "Masas iridiscentes de materia amorfa, con decenas de ojos verdes y bocas que se forman y colapsan al instante. Siervos creados por dioses que se rebelaron y devoraron a sus creadores.",
      },
    },
    {
      id: "ent04",
      art: ART.e04,
      original: "Illithid (Mind Flayer)",
      stats: { cr: 8, hp: 71, ca: 15 },
      attack: {
        pt: "Explosão Mental Psíquica",
        en: "Psychic Mind Blast",
        es: "Explosión Mental Psíquica",
      },
      special: {
        pt: " Extração Craniana",
        en: " Cranial Extraction",
        es: " Extracción Craneal",
        kind: "Habilidade",
      },
      name: {
        pt: "Devorador de Mentes",
        en: "Mind Flayer",
        es: "Devorador de Mentes",
      },
      lore: {
        pt: "Seres pálidos humanoides com tentáculos cefalopódicos no lugar do rosto. Viajantes astrais sádicos que se alimentam da sanidade e do córtex cerebral de intelectuais.",
        en: "Pale humanoid beings with cephalopod tentacles where their face should be. Sadistic astral travelers who feed on the sanity and cerebral cortex of intellectuals.",
        es: "Seres pálidos humanoides con tentáculos cefalópodos en lugar del rostro. Viajeros astrales sádicos que se alimentan de la cordura y el córtex cerebral de los intelectuales.",
      },
    },
    {
      id: "ent05",
      art: ART.e05,
      original: "Hound of Tindalos",
      stats: { cr: 12, hp: 110, ca: 16 },
      attack: {
        pt: "Teletransporte Angular",
        en: "Angular Teleportation",
        es: "Teletransporte Angular",
      },
      special: {
        pt: " Teletransporte Angular e Degradação de Tempo",
        en: " Angular Teleportation and Time Decay",
        es: " Teletransporte Angular y Degradación Temporal",
        kind: "Habilidade",
      },
      name: {
        pt: "Cão de Tindalos",
        en: "Hound of Tindalos",
        es: "Sabueso de Tíndalos",
      },
      lore: {
        pt: "Predadores macilentos que não habitam a física comum, mas os ângulos distorcidos do tempo. Perseguem pelo multiverso qualquer um tolo o suficiente para manipular a cronologia.",
        en: "Gaunt predators that dwell not in common physics, but in the distorted angles of time. They hunt across the multiverse anyone foolish enough to manipulate chronology.",
        es: "Depredadores macilentos que no habitan la física común, sino los ángulos distorsionados del tiempo. Persiguen por el multiverso a cualquiera lo bastante necio como para manipular la cronología.",
      },
    },
    {
      id: "ent06",
      art: ART.e06,
      original: "Star Vampire",
      stats: { cr: 10, hp: 95, ca: 15 },
      attack: {
        pt: "Drenagem de Sangue Súbita",
        en: "Sudden Blood Drain",
        es: "Drenaje de Sangre Súbito",
      },
      special: {
        pt: " Invisibilidade Natural Constante",
        en: " Constant Natural Invisibility",
        es: " Invisibilidad Natural Constante",
        kind: "Habilidade",
      },
      name: {
        pt: "Vampiro Estelar",
        en: "Star Vampire",
        es: "Vampiro Estelar",
      },
      lore: {
        pt: "Abominações originadas nos vazios entre os planetas. São impossíveis de serem vistos a olho nu; a única forma de notar sua aproximação é o som de um riso gorgolejante e a silhueta macabra que se forma temporariamente após eles se banharem no sangue das vítimas.",
        en: "Abominations born in the voids between the planets. They are impossible to see with the naked eye; the only way to notice their approach is the sound of a gurgling laughter and the macabre silhouette that forms temporarily after they bathe in their victims' blood.",
        es: "Abominaciones originadas en los vacíos entre los planetas. Son imposibles de ver a simple vista; la única forma de notar su aproximación es el sonido de una risa gorgoteante y la silueta macabra que se forma temporalmente tras bañarse en la sangre de sus víctimas.",
      },
    },
    {
      id: "ent07",
      art: ART.e07,
      original: "Colour Out of Space",
      stats: { cr: 14, hp: 120, ca: 12 },
      attack: {
        pt: "Envenenamento Radioativo",
        en: "Radioactive Poisoning",
        es: "Envenenamiento Radioactivo",
      },
      special: {
        pt: " Drenagem Passiva de Vida num raio de 10 metros",
        en: " Passive Life Drain within a 10-meter radius",
        es: " Drenaje Pasivo de Vida en un radio de 10 metros",
        kind: "Aura",
      },
      name: {
        pt: "A Cor que Caiu do Espaço",
        en: "The Colour Out of Space",
        es: "El Color que Cayó del Espacio",
      },
      lore: {
        pt: "Não é uma criatura, mas uma anomalia em estado gasoso. Um parasita cromático que infecta lençóis freáticos e solos, mutando toda a vida local para tons de cinza doentio até que as vítimas desmoronem em pó sem força para gritar.",
        en: "It is not a creature, but a gaseous anomaly. A chromatic parasite that infects groundwater and soil, mutating all local life into sickly grey tones until the victims crumble into dust without the strength to scream.",
        es: "No es una criatura, sino una anomalía en estado gaseoso. Un parásito cromático que infecta los mantos freáticos y los suelos, mutando toda la vida local hacia tonos de gris enfermizo hasta que las víctimas se desmoronan en polvo sin fuerzas para gritar.",
      },
    },
    {
      id: "ent08",
      art: ART.e08,
      original: "Flying Polyp",
      stats: { cr: 16, hp: 180, ca: 16 },
      attack: {
        pt: "Controle Ciclônico Extremo",
        en: "Extreme Cyclonic Control",
        es: "Control Ciclónico Extremo",
      },
      special: {
        pt: " Imunidade Absoluta a cortes não-mágicos",
        en: " Absolute Immunity to non-magical slashing",
        es: " Inmunidad Absoluta a cortes no mágicos",
        kind: "Imunidade",
      },
      name: { pt: "Pólipo Voador", en: "Flying Polyp", es: "Pólipo Volador" },
      lore: {
        pt: "Uma espécie ancestral desprovida de visão material. Habitam abismos escuros e cidades construídas em basalto sem janelas. Manipulam o clima, criam tornados assassinos e se comunicam através de assobios estridentes e pavorosos.",
        en: "An ancient species devoid of material sight. They inhabit dark abysses and windowless cities built of basalt. They manipulate the weather, create murderous tornadoes, and communicate through shrill, terrifying whistles.",
        es: "Una especie ancestral desprovista de visión material. Habitan abismos oscuros y ciudades construidas en basalto sin ventanas. Manipulan el clima, crean tornados asesinos y se comunican mediante silbidos estridentes y espantosos.",
      },
    },
    {
      id: "ent09",
      art: ART.e09,
      original: "Bhole / Dhole",
      stats: { cr: 24, hp: 400, ca: 22 },
      attack: {
        pt: "Devorar Montanhas (Engolir Inteiro)",
        en: "Devour Mountains (Swallow Whole)",
        es: "Devorar Montañas (Engullir Entero)",
      },
      special: {
        pt: " Tremor de Terra Cataclísmico",
        en: " Cataclysmic Earthquake",
        es: " Terremoto Cataclísmico",
        kind: "Ataque",
      },
      name: {
        pt: "Verme do Abismo",
        en: "Abyss Worm",
        es: "Gusano del Abismo",
      },
      lore: {
        pt: "Titãs subterrâneos que devoram a fundação geológica de mundos mortos. Cegos e pálidos, eles cospem magma e ácido para abrir túneis cósmicos por onde seus Deuses Exteriores caminham.",
        en: "Subterranean titans that devour the geological foundation of dead worlds. Blind and pale, they spit magma and acid to carve cosmic tunnels through which their Outer Gods walk.",
        es: "Titanes subterráneos que devoran los cimientos geológicos de mundos muertos. Ciegos y pálidos, escupen magma y ácido para abrir túneles cósmicos por donde caminan sus Dioses Exteriores.",
      },
    },
    {
      id: "ent10",
      art: ART.e10,
      original: "Nightgaunt",
      stats: { cr: 6, hp: 55, ca: 14 },
      attack: {
        pt: " Sufocamento Tátil",
        en: " Tactile Suffocation",
        es: " Asfixia Táctil",
      },
      special: {
        pt: " Visão às Cegas",
        en: " Blindsight",
        es: " Visión Ciega",
        kind: "Habilidade",
      },
      name: {
        pt: "Rastejador Obscuro",
        en: "Nightgaunt",
        es: "Rastrero Oscuro",
      },
      lore: {
        pt: "Servos esguios com pele que lembra borracha preta e grandes asas de morcego. Possuem chifres curvos e são completamente desprovidos de rostos. Descem dos céus noturnos em silêncio absoluto para capturar e abandonar suas vítimas em dimensões de pesadelo.",
        en: "Slender servants with skin resembling black rubber and large bat wings. They have curved horns and are entirely faceless. They descend from the night skies in absolute silence to capture their victims and abandon them in nightmare dimensions.",
        es: "Siervos esbeltos con piel que recuerda al caucho negro y grandes alas de murciélago. Poseen cuernos curvos y carecen por completo de rostro. Descienden de los cielos nocturnos en silencio absoluto para capturar y abandonar a sus víctimas en dimensiones de pesadilla.",
      },
    },
  ];

  const ORACLE = {
    geo: [
      {
        pt: "Biblioteca Soterrada de Pnakotus",
        en: "Buried Library of Pnakotus",
        es: "Biblioteca Sepultada de Pnakotus",
      },
      {
        pt: "Altar Ciclópico de K'n-yan",
        en: "Cyclopean Altar of K'n-yan",
        es: "Altar Ciclópeo de K'n-yan",
      },
      {
        pt: "Laboratório Alquímico Corrompido",
        en: "Corrupted Alchemical Laboratory",
        es: "Laboratorio Alquímico Corrompido",
      },
      {
        pt: "Litoral Neoeuclidiano Coberto por Névoa Espessa",
        en: "Neo-Euclidean Coast Shrouded in Thick Fog",
        es: "Litoral Neoeuclidiano Cubierto por Niebla Espesa",
      },
      {
        pt: "Catedral Invertida sob o Gelo Antártico",
        en: "Inverted Cathedral beneath the Antarctic Ice",
        es: "Catedral Invertida bajo el Hielo Antártico",
      },
      {
        pt: "Esgoto Não-Euclidiano da Cidade Esquecida",
        en: "Non-Euclidean Sewer of the Forgotten City",
        es: "Alcantarilla No-Euclidiana de la Ciudad Olvidada",
      },
    ],
    insanity: [
      {
        pt: {
          t: "Sussurros Obscuros",
          d: "Estatísticas de rolagem dos jogadores caem pela metade no primeiro turno.",
        },
        en: {
          t: "Obscure Whispers",
          d: "Players' roll statistics are halved during the first turn.",
        },
        es: {
          t: "Susurros Oscuros",
          d: "Las estadísticas de tirada de los jugadores se reducen a la mitad en el primer turno.",
        },
      },
      {
        pt: {
          t: "Distorção Cronológica",
          d: "A fluidez do tempo quebra. As rodadas de ataque sofrem restrições de movimento extremo.",
        },
        en: {
          t: "Chronological Distortion",
          d: "The flow of time breaks. Attack rounds suffer extreme movement restrictions.",
        },
        es: {
          t: "Distorsión Cronológica",
          d: "La fluidez del tiempo se quiebra. Las rondas de ataque sufren restricciones de movimiento extremo.",
        },
      },
      {
        pt: {
          t: "Fobia Paralisante",
          d: "Condiciona um ataque de pânico automático se o jogador possuir um alinhamento incompatível com o terreno gerado.",
        },
        en: {
          t: "Paralyzing Phobia",
          d: "Triggers an automatic panic attack if the player has an alignment incompatible with the generated terrain.",
        },
        es: {
          t: "Fobia Paralizante",
          d: "Provoca un ataque de pánico automático si el jugador posee un alineamiento incompatible con el terreno generado.",
        },
      },
    ],
  };

  const I18N = {
    pt: {
      langName: "Português",
      brandSub: "Terminal Investigativo · Horror Cósmico",
      portalTitle: "O Arquivo do Insondável",
      portalSub:
        " Antes que o Vazio lhe observe de volta, declare a sua natureza. O token que escolher será gravado nas profundezas e selará as suas permissões.",
      master: "Guardião dos Segredos",
      masterRole: "Mestre",
      player: "Investigador",
      playerRole: "Jogador",
      masterPerks: [
        " Roteamento irrestrito e controle total",
        " Bestiário com Estatísticas Vitais reveladas",
        " Acesso ao Oráculo de geração procedural",
        " Modificadores Catastróficos de letalidade",
      ],
      playerPerks: [
        " Diário de Descobertas e rumores",
        " Dados vitais ocultos sob cadeado",
        " Oráculo suprimido",
        " Ficha de Investigador privada e persistente",
      ],
      enter: "Atravessar o Limiar",
      navBestiary: "Bestiário",
      navOracle: "Oráculo",
      navSheet: "Ficha",
      navPortal: "Portal",
      bestiaryTitle: "O Bestiário",
      bestiaryDescMaster:
        "Catalogação de dez ameaças. Como Guardião, tem acesso aos contos macabros E as Estatísticas Vitais selecionadas para o massacre.",
      bestiaryDescPlayer:
        "Diário de Descobertas. Tu vê a imagem e lê os rumores. Os dados vitais permanecem trancados — o conhecimento proibido corrompe.",
      search: "Pesquisar / Filtrar Entidade: ",
      vitalStats: "Estatísticas Vitais",
      lore: "Rumores Documentados",
      locked: "DADOS SELADOS",
      lockedSub: "Acesso exclusivo do Guardião",
      cr: "Nível de Desafio",
      hp: "Pontos de Vida",
      ca: "Classe de Armadura",
      attack: "Ataque",
      oracleTitle: "O Oráculo",
      oracleDesc:
        "Invoca uma cena de perigo. O motor cruza um Vetor Geográfico, uma Ameaça do Bestiário e uma Condição de Insanidade.",
      invoke: "Consultar o Vazio",
      invoking: "O Vazio responde...",
      famine: "Fome Extrema (letalidade dobrada)",
      catastrophic: "Modificadores Catastróficos",
      axisGeo: "Vetor Geográfico",
      axisThreat: "Ameaça Direta",
      axisInsanity: "Em caso de Insanidade:",
      noResult: "O Vazio aguarda tua consulta.",
      sheetTitle: "Ficha do Investigador",
      sheetDesc:
        "Cada fragmento é gravado em tempo real na memória local desta máquina. Recarregue: nada será perdido.",
      identity: "Identidade",
      occupation: "Ocupação Acadêmica",
      age: "Idade",
      origin: "Local de Origem",
      attributes: "Atributos Clínicos",
      vitality: "Sanidade & Vida",
      arsenal: "Arsenal & Perícias",
      maxHp: "Vida Máxima",
      curSanity: "Sanidade Atual",
      inventory: "Inventário Balístico e Arcano",
      skills: "Perícias",
      saved: "✓ Gravado no disco do navegador",
      accessDenied: "ACESSO NEGADO",
      accessDeniedMsg:
        "O Oráculo está selado para Investigadores. Apenas o Mestre dos pode acessar o Vazio.",
      sheetDeniedMsg: "A Ficha do Investigador é privada.",
      sanityLabel: "Sanidade do Grupo",
      changeProfile: "Trocar Perfil",
      str: "Força",
      dex: "Destreza",
      con: "Constituição",
      int: "Inteligência",
      wis: "Sabedoria",
      cha: "Carisma",
      skillList: [
        "Ocultismo",
        "Medicina",
        "Línguas Mortas",
        "Furtividade",
        "Investigação",
        "História",
        "Arcanismo",
        "Intimidação",
      ],
    },
    en: {
      langName: "English",
      brandSub: "Investigative Terminal · Cosmic Horror",
      portalTitle: "The Archive of the Unfathomable",
      portalSub:
        "Before the Void gazes back at you, declare your nature. The token of your choice shall be carved into the depths of this machine and seal your permissions.",
      master: "Keeper of Secrets",
      masterRole: "Master",
      player: "Investigator",
      playerRole: "Player",
      masterPerks: [
        "Unrestricted routing and total control",
        "Bestiary with revealed Vital Statistics",
        "Access to the procedural Oracle",
        "Catastrophic lethality modifiers",
      ],
      playerPerks: [
        "Diary of Discoveries and rumors",
        "Vital data hidden under lock",
        "Oracle suppressed",
        "Private, persistent Investigator Sheet",
      ],
      enter: "Cross the Threshold",
      navBestiary: "Bestiary",
      navOracle: "Oracle",
      navSheet: "Sheet",
      navPortal: "Portal",
      bestiaryTitle: "The Bestiary",
      bestiaryDescMaster:
        "Exhaustive cataloguing of ten threats. As Keeper, you behold the macabre tales AND the Vital Statistics selected for the slaughter.",
      bestiaryDescPlayer:
        "Diary of Discoveries. You see the image and read the rumors. Vital data remains locked — forbidden knowledge corrupts.",
      search: "Cross-reference the archive...",
      vitalStats: "Vital Statistics",
      lore: "Documented Rumors",
      locked: "SEALED DATA",
      lockedSub: "Keeper-exclusive access",
      cr: "Challenge Rating",
      hp: "Hit Points",
      ca: "Armor Class",
      attack: "Attack",
      oracleTitle: "The Oracle",
      oracleDesc:
        "Invoke a scene of peril. The engine cross-references a Geographic Vector, a Bestiary Threat, and an Insanity Conditioner.",
      invoke: "Consult the Void",
      invoking: "The Void responds...",
      famine: "Extreme Hunger (doubled lethality)",
      catastrophic: "Catastrophic Modifiers",
      axisGeo: "Geographic Vector",
      axisThreat: "Direct Threat",
      axisInsanity: "Insanity Conditioner",
      noResult: "The Void awaits your consultation.",
      sheetTitle: "Investigator Sheet",
      sheetDesc:
        "Every fragment is written in real time to this machine's local memory. Reload: nothing will be lost.",
      identity: "Identity",
      occupation: "Academic Occupation",
      age: "Age",
      origin: "Place of Origin",
      attributes: "Clinical Attributes",
      vitality: "Sanity & Life",
      arsenal: "Arsenal & Skills",
      maxHp: "Maximum Life",
      curSanity: "Current Sanity",
      inventory: "Ballistic & Arcane Inventory",
      skills: "Skills",
      saved: "✓ Saved to browser disk",
      accessDenied: "ACCESS DENIED",
      accessDeniedMsg:
        "The Oracle is sealed to Investigators. Only the Keeper of Secrets invokes the Void.",
      sheetDeniedMsg:
        "The Investigator Sheet is private and absent from the Keeper's profile.",
      sanityLabel: "Party Sanity",
      changeProfile: "Switch Profile",
      str: "Strength",
      dex: "Dexterity",
      con: "Constitution",
      int: "Intelligence",
      wis: "Wisdom",
      cha: "Charisma",
      skillList: [
        "Occult",
        "Medicine",
        "Dead Languages",
        "Stealth",
        "Investigation",
        "History",
        "Arcana",
        "Intimidation",
      ],
    },
    es: {
      langName: "Español",
      brandSub: "Terminal Investigativa · Horror Cósmico",
      portalTitle: "El Archivo de lo Insondable",
      portalSub:
        "Antes de que el Vacío te observe a su vez, declara tu naturaleza. El testigo de tu elección quedará grabado en las profundidades de esta máquina y sellará tus permisos.",
      master: "Guardián de los Secretos",
      masterRole: "Máster",
      player: "Investigador",
      playerRole: "Jugador",
      masterPerks: [
        "Enrutamiento irrestricto y control total",
        "Bestiario con Estadísticas Vitales reveladas",
        "Acceso al Oráculo de generación procedural",
        "Modificadores Catastróficos de letalidad",
      ],
      playerPerks: [
        "Diario de Descubrimientos y rumores",
        "Datos vitales ocultos bajo candado",
        "Oráculo suprimido",
        "Ficha de Investigador privada y persistente",
      ],
      enter: "Cruzar el Umbral",
      navBestiary: "Bestiario",
      navOracle: "Oráculo",
      navSheet: "Ficha",
      navPortal: "Portal",
      bestiaryTitle: "El Bestiario",
      bestiaryDescMaster:
        "Catalogación exhaustiva de diez amenazas. Como Guardián, contemplas los relatos macabros Y las Estadísticas Vitales seleccionadas para la masacre.",
      bestiaryDescPlayer:
        "Diario de Descubrimientos. Tú ves la imagen y lees los rumores. Los datos vitales permanecen bajo candado — el conocimiento prohibido corrompe.",
      search: "Cruzar datos del archivo...",
      vitalStats: "Estadísticas Vitales",
      lore: "Rumores Documentados",
      locked: "DATOS SELLADOS",
      lockedSub: "Acceso exclusivo del Guardián",
      cr: "Nivel de Desafío",
      hp: "Puntos de Vida",
      ca: "Clase de Armadura",
      attack: "Ataque",
      oracleTitle: "El Oráculo",
      oracleDesc:
        "Invoca una escena de peligro. El motor cruza un Vector Geográfico, una Amenaza del Bestiario y una Condicionante de Demencia.",
      invoke: "Consultar el Vacío",
      invoking: "El Vacío responde...",
      famine: "Hambre Extrema (letalidad duplicada)",
      catastrophic: "Modificadores Catastróficos",
      axisGeo: "Vector Geográfico",
      axisThreat: "Amenaza Directa",
      axisInsanity: "Condicionante de Demencia",
      noResult: "El Vacío aguarda tu consulta.",
      sheetTitle: "Ficha del Investigador",
      sheetDesc:
        "Cada fragmento se graba en tiempo real en la memoria local de esta máquina. Recarga: nada se perderá.",
      identity: "Identidad",
      occupation: "Ocupación Académica",
      age: "Edad",
      origin: "Lugar de Origen",
      attributes: "Atributos Clínicos",
      vitality: "Cordura y Vida",
      arsenal: "Arsenal y Pericias",
      maxHp: "Vida Máxima",
      curSanity: "Cordura Actual",
      inventory: "Inventario Balístico y Arcano",
      skills: "Pericias",
      saved: "✓ Grabado en el disco del navegador",
      accessDenied: "ACCESO DENEGADO",
      accessDeniedMsg:
        "El Oráculo está sellado para los Investigadores. Solo el Guardián de los Secretos invoca el Vacío.",
      sheetDeniedMsg:
        "La Ficha del Investigador es privada y está ausente del perfil del Guardián.",
      sanityLabel: "Cordura del Grupo",
      changeProfile: "Cambiar Perfil",
      str: "Fuerza",
      dex: "Destreza",
      con: "Constitución",
      int: "Inteligencia",
      wis: "Sabiduría",
      cha: "Carisma",
      skillList: [
        "Ocultismo",
        "Medicina",
        "Lenguas Muertas",
        "Sigilo",
        "Investigación",
        "Historia",
        "Arcanos",
        "Intimidación",
      ],
    },
  };

  window.ARCHIVE_DATA = { BESTIARY: BESTIARY, ORACLE: ORACLE, I18N: I18N };
})();
